### ISSUE TITLE
Checkpoint Release

### ISSUE THREAD

**Issue by Cao-Cong0** [Det1999/ShapeMaker#1]
Hi! Your work is so amazing!
May I ask if you have the plan to release the checkpoint?

**Comment by shangbuhuan13** [comment]
Thank you for your interest in our work. We will upload the ckpt before Monday next week. Thank you
@Cao-Cong0 @zero-joke

**Comment by Cao-Cong0** [comment]
> Thank you for your interest in our work. We will upload the ckpt before Monday next week. Thank you @Cao-Cong0 @zero-joke

Thanks a lot!
