### ISSUE TITLE
Easy set up

### ISSUE THREAD

**Issue by zero-joke** [Det1999/ShapeMaker#2]
Thanks for your amazing work! And I have some questions.
1. How to write a simple demo that input a point cloud or mesh ,then get the result of shape through R&D of ShapeMaker.I would like to refer to ''cage_EVAL.py to write it, but the dataloader is complex，can you give me some suggestion.
2. The output shape's pose and size will be adjusted to match the input one, did  I understand correctly?

**Comment by shangbuhuan13** [comment]
I can first answer your second question. 
Yes, the pose and size will be adjusted, and the shape of the retrieved shape will also be slightly adjusted (in the cage based deformation module) to match the input one.

**Comment by shangbuhuan13** [comment]
For the first question, we will provide the checkpoint next week. For a single test, the simplest way I think may be directly changing the __get_item__ function in the dataloader. You can directly modify it to return your own point cloud.
